export default [
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 188,
      top: 16,
      left: 0,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 221,
      top: 55,
      left: 65,
      zIndex: 2,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 160,
      top: 18,
      left: 42,
      zIndex: 0,
    },
    {
      startIndex: 450,
      numImages: 150,
      duration: 3,
      size: 137,
      top: 2,
      left: 72,
      zIndex: 0,
    },
    {
      startIndex: 600,
      numImages: 150,
      duration: 3,
      size: 269,
      top: 44,
      left: 8,
      zIndex: 0,
    },
    {
      startIndex: 750,
      numImages: 150,
      duration: 3,
      size: 205,
      top: 0,
      left: 12,
      zIndex: 0,
    },
    {
      startIndex: 900,
      numImages: 150,
      duration: 3,
      size: 158,
      top: 77,
      left: 50,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 162,
      top: 42,
      left: 28,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 122,
      top: 2,
      left: 55,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 197,
      top: 70,
      left: 62,
      zIndex: 0,
    },
    {
      startIndex: 450,
      numImages: 150,
      duration: 3,
      size: 162,
      top: 72,
      left: 8,
      zIndex: 0,
    },
    {
      startIndex: 600,
      numImages: 150,
      duration: 3,
      size: 122,
      top: 32,
      left: 5,
      zIndex: 2,
    },
    {
      startIndex: 750,
      numImages: 150,
      duration: 3,
      size: 197,
      top: 20,
      left: 58,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 248,
      top: 20,
      left: 80,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 101,
      top: 21,
      left: 52,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 116,
      top: 61,
      left: 15,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 198,
      top: 83,
      left: 22,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 277,
      top: 41,
      left: 75,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 292,
      top: 56,
      left: 5,
      zIndex: 0,
    },
    {
      startIndex: 450,
      numImages: 150,
      duration: 3,
      size: 100,
      top: 5,
      left: 30,
      zIndex: 2,
    },
    {
      startIndex: 600,
      numImages: 150,
      duration: 3,
      size: 156,
      top: 83,
      left: 52,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 121,
      top: 88,
      left: 15,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 256,
      top: 83,
      left: 42,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 174,
      top: 56,
      left: 60,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 140,
      top: 80,
      left: 12,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 158,
      top: 61,
      left: 40,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 240,
      top: 53,
      left: 25,
      zIndex: 2,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 157,
      top: 97,
      left: 20,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 227,
      top: 21,
      left: 55,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 273,
      top: 53,
      left: 35,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 294,
      top: 39,
      left: 5,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 166,
      top: 52,
      left: 32,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 192,
      top: 66,
      left: 22,
      zIndex: 0,
    },
    {
      startIndex: 450,
      numImages: 150,
      duration: 3,
      size: 132,
      top: 33,
      left: 58,
      zIndex: 2,
    },
    {
      startIndex: 600,
      numImages: 150,
      duration: 3,
      size: 297,
      top: 45,
      left: 12,
      zIndex: 0,
    },
    {
      startIndex: 750,
      numImages: 150,
      duration: 3,
      size: 237,
      top: 55,
      left: 40,
      zIndex: 0,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 174,
      top: 60,
      left: 10,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 192,
      top: 37,
      left: 55,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 176,
      top: 75,
      left: 28,
      zIndex: 2,
    },
  ],
  [
    {
      startIndex: 0,
      numImages: 150,
      duration: 3,
      size: 280,
      top: 61,
      left: 18,
      zIndex: 0,
    },
    {
      startIndex: 150,
      numImages: 150,
      duration: 3,
      size: 163,
      top: 86,
      left: 62,
      zIndex: 0,
    },
    {
      startIndex: 300,
      numImages: 150,
      duration: 3,
      size: 144,
      top: 21,
      left: 32,
      zIndex: 0,
    },
    {
      startIndex: 450,
      numImages: 150,
      duration: 3,
      size: 208,
      top: 53,
      left: 65,
      zIndex: 0,
    },
  ],
];
